// <auto-generated />
using System;
using Infrastructure.Data.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.SQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004205602_ADD_PARTICIPANTS_CHATS_RH")]
    partial class ADD_PARTICIPANTS_CHATS_RH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.Property<int>("IDArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDArchivo"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("IDRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDArchivo");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("IDRespuesta");

                    b.ToTable("Archivos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Property<int>("IDEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEtiqueta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DescripcionEtiqueta")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NombreEtiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDEtiqueta");

                    b.ToTable("Etiquetas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.Property<int>("IDEtiquetaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEtiquetaPublicacion"));

                    b.Property<int>("IDEtiqueta")
                        .HasColumnType("int");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.HasKey("IDEtiquetaPublicacion");

                    b.HasIndex("IDEtiqueta");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("EtiquetasPublicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetasPrediccionModeloModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte[]>("ModelData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("EtiquetasPrediccionModelo", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Property<int>("IDMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMedalla"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagenMedalla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMedalla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDMedalla");

                    b.ToTable("Medallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.NotificacionesModel", b =>
                {
                    b.Property<int>("IDNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNotificacion"));

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNotificacion");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.Property<int>("IDPublicacionGuardada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPublicacionGuardada"));

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDPublicacionGuardada");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("PublicacionesGuardadas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPublicacion"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Recompensa")
                        .HasColumnType("int");

                    b.Property<bool>("Respondida")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visitas")
                        .HasColumnType("int");

                    b.HasKey("IDPublicacion");

                    b.ToTable("Publicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.HasKey("IDPublicacion", "IDUsuario");

                    b.ToTable("PublicacionesVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Property<int>("IDRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRecompensa"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IDRecompensa");

                    b.ToTable("Recompensas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.Property<int>("IDRecompensaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRecompensaUsuario"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaObtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IDRecompensa")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDRecompensaUsuario");

                    b.HasIndex("IDRecompensa");

                    b.ToTable("RecompensasUsuario", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRespuesta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("RespuestaCorrecta")
                        .HasColumnType("bit");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDRespuesta");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("Respuestas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.HasKey("IDRespuesta", "IDUsuario");

                    b.ToTable("RespuestasVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaModel", b =>
                {
                    b.Property<Guid>("IDSesion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IDReserva")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDSesion");

                    b.HasIndex("IDReserva")
                        .IsUnique()
                        .HasDatabaseName("IX_SesionAyuda_Reserva");

                    b.HasIndex("Dominio", "NombreSala")
                        .IsUnique()
                        .HasDatabaseName("UQ_SesionAyuda_Sala");

                    b.ToTable("SesionAyuda", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeLecturaModel", b =>
                {
                    b.Property<int>("IDMensaje")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDMensaje", "IDUsuario");

                    b.HasIndex("IDUsuario")
                        .HasDatabaseName("IX_SAChatMsgRead_User");

                    b.ToTable("SolicitudAyudaChatMensajeLectura", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.Property<int>("IDMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMensaje"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IDChat")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMensaje");

                    b.HasIndex("IDChat")
                        .HasDatabaseName("IX_SAChatMsg_Chat");

                    b.HasIndex("IDChat", "CreateDate")
                        .HasDatabaseName("IX_SAChatMsg_ChatDate");

                    b.ToTable("SolicitudAyudaChatMensaje", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.Property<int>("IDChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChat"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuarioAyudante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDChat");

                    b.HasIndex("IDUsuarioAyudante")
                        .HasDatabaseName("IX_SAChat_Ayudante");

                    b.HasIndex("IDSolicitudAyuda", "IDUsuarioAyudante")
                        .IsUnique()
                        .HasDatabaseName("UQ_SAChat_SolicitudAyudante");

                    b.ToTable("SolicitudAyudaChat", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatParticipanteModel", b =>
                {
                    b.Property<int>("IDChat")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint");

                    b.HasKey("IDChat", "IDUsuario");

                    b.HasIndex("IDChat", "Rol")
                        .IsUnique()
                        .HasDatabaseName("UQ_SCP_ChatRol");

                    b.ToTable("SolicitudAyudaChatParticipante", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.Property<int>("IDDisponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDisponibilidad"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDDisponibilidad");

                    b.HasIndex("IDSolicitudAyuda")
                        .HasDatabaseName("IX_SAD_Solicitud");

                    b.HasIndex("Estado", "Inicio")
                        .HasDatabaseName("IX_SAD_EstadoTiempo");

                    b.ToTable("SolicitudAyudaDisponibilidad", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEstadoModel", b =>
                {
                    b.Property<int>("IDEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEstado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDEstado");

                    b.HasIndex("Estado")
                        .IsUnique()
                        .HasDatabaseName("UQ_SolicitudAyudaEstado_Estado");

                    b.ToTable("SolicitudAyudaEstado", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEtiquetasModel", b =>
                {
                    b.Property<int>("IDSolicitudAyudaEtiquetas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSolicitudAyudaEtiquetas"));

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("int");

                    b.Property<int>("IDEtiqueta")
                        .HasColumnType("int");

                    b.HasKey("IDSolicitudAyudaEtiquetas", "IDSolicitudAyuda", "IDEtiqueta");

                    b.HasIndex("IDEtiqueta");

                    b.HasIndex("IDSolicitudAyuda", "IDEtiqueta")
                        .IsUnique()
                        .HasDatabaseName("UX_SolicitudAyudaEtiquetas");

                    b.ToTable("SolicitudAyudaEtiquetas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaHistorialModel", b =>
                {
                    b.Property<int>("IDHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHistorial"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte?>("EstadoAnterior")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EstadoNuevo")
                        .HasColumnType("tinyint");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserIdAccion")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDHistorial");

                    b.HasIndex("IDSolicitudAyuda", "CreateDate")
                        .HasDatabaseName("IX_SAH_Solicitud");

                    b.ToTable("SolicitudAyudaHistorial", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.Property<int>("IDSolicitudAyuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSolicitudAyuda"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IDEstado")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuarioSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("IncrementoPorHora")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("Lenguaje")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RecompensaBase")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Urgencia")
                        .HasColumnType("tinyint");

                    b.HasKey("IDSolicitudAyuda");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("IX_SA_Vencimiento");

                    b.HasIndex("IDEstado")
                        .HasDatabaseName("IX_SA_IDEstado");

                    b.HasIndex("IDUsuarioSolicitante")
                        .HasDatabaseName("IX_SA_Solicitante");

                    b.ToTable("SolicitudAyuda", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.Property<int>("IDReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDReserva"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<int>("IDDisponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuarioAyudante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDReserva");

                    b.HasIndex("IDDisponibilidad")
                        .IsUnique()
                        .HasDatabaseName("UX_SolRes_Disponibilidad_Activa")
                        .HasFilter("([Estado] IN (0,1,2))");

                    b.HasIndex("IDUsuarioAyudante", "Estado")
                        .HasDatabaseName("IX_SolRes_Ayudante");

                    b.ToTable("SolicitudAyudaReserva", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.TextoPrediccionModel", b =>
                {
                    b.Property<int>("IDTextoPrediccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTextoPrediccion"));

                    b.Property<string>("Etiquetas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTextoPrediccion");

                    b.ToTable("TextoPredicciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.Property<int>("IDUsuarioMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuarioMedalla"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDMedalla")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDUsuarioMedalla");

                    b.HasIndex("IDMedalla");

                    b.ToTable("UsuariosMedallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Views.TopTenPublicationsLastWeekView", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_topTenPublicationsLastWeek", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Views.TopThreeUsersLastWeekView", b =>
                {
                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecompensa")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_topThreeUsersLastWeek", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Archivos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("Archivos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.HasOne("Core.Domain.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("EtiquetasPublicaciones")
                        .HasForeignKey("IDEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("EtiquetasPublicacion")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesGuardadas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesVotos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RecompensaModel", "Recompensa")
                        .WithMany("RecompensasUsuarios")
                        .HasForeignKey("IDRecompensa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("RespuestasVotos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaReservaModel", "Reserva")
                        .WithOne("Sesion")
                        .HasForeignKey("Core.Domain.Models.SesionAyudaModel", "IDReserva")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeLecturaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatMensajeModel", "Mensaje")
                        .WithMany("Lecturas")
                        .HasForeignKey("IDMensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatModel", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("IDChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Chats")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatParticipanteModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatModel", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("IDChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEtiquetasModel", b =>
                {
                    b.HasOne("Core.Domain.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("SolicitudAyudaEtiquetas")
                        .HasForeignKey("IDEtiqueta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("SolicitudAyudaEtiquetas")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaHistorialModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Historial")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaEstadoModel", "SolicitudAyudaEstado")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IDEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SolicitudAyudaEstado");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", "Disponibilidad")
                        .WithMany("Reservas")
                        .HasForeignKey("IDDisponibilidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Disponibilidad");
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.MedallaModel", "Medalla")
                        .WithMany("UsuariosMedallas")
                        .HasForeignKey("IDMedalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medalla");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Navigation("EtiquetasPublicaciones");

                    b.Navigation("SolicitudAyudaEtiquetas");
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Navigation("UsuariosMedallas");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("EtiquetasPublicacion");

                    b.Navigation("PublicacionesGuardadas");

                    b.Navigation("PublicacionesVotos");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Navigation("RecompensasUsuarios");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("RespuestasVotos");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEstadoModel", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Historial");

                    b.Navigation("SolicitudAyudaEtiquetas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.Navigation("Sesion");
                });
#pragma warning restore 612, 618
        }
    }
}
