// <auto-generated />
using System;
using Infrastructure.Data.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.SQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729004411_ALTER_TABLE_NOTIFICACIONES")]
    partial class ALTER_TABLE_NOTIFICACIONES
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.Property<int>("IDArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDArchivo"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("IDRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDArchivo");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("IDRespuesta");

                    b.ToTable("Archivos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Property<int>("IDEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEtiqueta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NombreEtiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDEtiqueta");

                    b.ToTable("Etiquetas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.Property<int>("IDEtiquetaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEtiquetaPublicacion"));

                    b.Property<int>("IDEtiqueta")
                        .HasColumnType("int");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.HasKey("IDEtiquetaPublicacion");

                    b.HasIndex("IDEtiqueta");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("EtiquetasPublicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetasPrediccionModeloModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte[]>("ModelData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("EtiquetasPrediccionModelo", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Property<int>("IDMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMedalla"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagenMedalla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMedalla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDMedalla");

                    b.ToTable("Medallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.NotificacionesModel", b =>
                {
                    b.Property<int>("IDNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNotificacion"));

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNotificacion");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.Property<int>("IDPublicacionGuardada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPublicacionGuardada"));

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDPublicacionGuardada");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("PublicacionesGuardadas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPublicacion"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Recompensa")
                        .HasColumnType("int");

                    b.Property<bool>("Respondida")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visitas")
                        .HasColumnType("int");

                    b.HasKey("IDPublicacion");

                    b.ToTable("Publicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.HasKey("IDPublicacion", "IDUsuario");

                    b.ToTable("PublicacionesVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Property<int>("IDRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRecompensa"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IDRecompensa");

                    b.ToTable("Recompensas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.Property<int>("IDRecompensaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRecompensaUsuario"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaObtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IDRecompensa")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDRecompensaUsuario");

                    b.HasIndex("IDRecompensa");

                    b.ToTable("RecompensasUsuario", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRespuesta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("RespuestaCorrecta")
                        .HasColumnType("bit");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IDRespuesta");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("Respuestas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.HasKey("IDRespuesta", "IDUsuario");

                    b.ToTable("RespuestasVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.TextoPrediccionModel", b =>
                {
                    b.Property<int>("IDTextoPrediccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTextoPrediccion"));

                    b.Property<string>("Etiquetas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTextoPrediccion");

                    b.ToTable("TextoPredicciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.Property<int>("IDUsuarioMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuarioMedalla"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDMedalla")
                        .HasColumnType("int");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDUsuarioMedalla");

                    b.HasIndex("IDMedalla");

                    b.ToTable("UsuariosMedallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Views.TopTenPublicationsLastWeekView", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_topTenPublicationsLastWeek", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Views.TopThreeUsersLastWeekView", b =>
                {
                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecompensa")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_topThreeUsersLastWeek", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Archivos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("Archivos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.HasOne("Core.Domain.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("EtiquetasPublicaciones")
                        .HasForeignKey("IDEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("EtiquetasPublicacion")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesGuardadas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesVotos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RecompensaModel", "Recompensa")
                        .WithMany("RecompensasUsuarios")
                        .HasForeignKey("IDRecompensa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("RespuestasVotos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.MedallaModel", "Medalla")
                        .WithMany("UsuariosMedallas")
                        .HasForeignKey("IDMedalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medalla");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Navigation("EtiquetasPublicaciones");
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Navigation("UsuariosMedallas");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("EtiquetasPublicacion");

                    b.Navigation("PublicacionesGuardadas");

                    b.Navigation("PublicacionesVotos");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Navigation("RecompensasUsuarios");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("RespuestasVotos");
                });
#pragma warning restore 612, 618
        }
    }
}
