<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.15" />
    <PackageReference Include="MimeKit" Version="4.0.0" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrossCutting.Helpers\CrossCutting.Helpers.csproj" />
  </ItemGroup>

</Project>
