// <auto-generated />
using System;
using Infrastructure.Data.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.SQL.Migrations.Gateway
{
    [DbContext(typeof(ApplicationGatewayDbContext))]
    [Migration("20251123005151_InitialPostgresGateway")]
    partial class InitialPostgresGateway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.IdentityModels.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.RolesClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesClaim", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(7) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LanguagePreference")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersClaims", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLogin", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsersToken", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.Property<int>("IDArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDArchivo"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("integer");

                    b.Property<int>("IDRespuesta")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDArchivo");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("IDRespuesta");

                    b.ToTable("Archivos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.DenunciaModel", b =>
                {
                    b.Property<int>("IDDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDenuncia"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FechaDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IDPublicacion")
                        .HasColumnType("integer");

                    b.Property<int?>("IDRespuesta")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuarioReporto")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDDenuncia");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("IDRespuesta");

                    b.HasIndex("IDUsuarioReporto");

                    b.ToTable("Denuncias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Denuncias_PublicacionOrRespuesta", "((\"IDPublicacion\" IS NOT NULL AND \"IDRespuesta\" IS NULL) OR (\"IDPublicacion\" IS NULL AND \"IDRespuesta\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Property<int>("IDEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEtiqueta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescripcionEtiqueta")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("NombreEtiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDEtiqueta");

                    b.ToTable("Etiquetas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.Property<int>("IDEtiquetaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEtiquetaPublicacion"));

                    b.Property<int>("IDEtiqueta")
                        .HasColumnType("integer");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("integer");

                    b.HasKey("IDEtiquetaPublicacion");

                    b.HasIndex("IDEtiqueta");

                    b.HasIndex("IDPublicacion");

                    b.ToTable("EtiquetasPublicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetasPrediccionModeloModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("ModelData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("EtiquetasPrediccionModelo", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.FilterModel", b =>
                {
                    b.Property<int>("IDFilter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDFilter"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Api")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IDFilterType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Options")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("IDFilter");

                    b.HasIndex("IDFilterType");

                    b.ToTable("Filter", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.FilterTypeModel", b =>
                {
                    b.Property<int>("IDFilterType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDFilterType"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.HasKey("IDFilterType");

                    b.ToTable("FilterType", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.GroupFiltersModel", b =>
                {
                    b.Property<int>("IDGroup")
                        .HasColumnType("integer");

                    b.Property<int>("IDFilter")
                        .HasColumnType("integer");

                    b.HasKey("IDGroup", "IDFilter");

                    b.HasIndex("IDFilter");

                    b.ToTable("GroupFilters", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.GroupModel", b =>
                {
                    b.Property<int>("IDGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDGroup"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IDGroup");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Property<int>("IDMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDMedalla"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImagenMedalla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMedalla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDMedalla");

                    b.ToTable("Medallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.NotificacionesModel", b =>
                {
                    b.Property<int>("IDNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDNotificacion"));

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("IDNotificacion");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.Property<int>("IDPublicacionGuardada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDPublicacionGuardada"));

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("IDPublicacionGuardada");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("IDUsuario");

                    b.ToTable("PublicacionesGuardadas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDPublicacion"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Recompensa")
                        .HasColumnType("integer");

                    b.Property<bool>("Respondida")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.Property<int>("Visitas")
                        .HasColumnType("integer");

                    b.HasKey("IDPublicacion");

                    b.HasIndex("UsersId");

                    b.ToTable("Publicaciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.Property<int>("IDPublicacion")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Positivo")
                        .HasColumnType("boolean");

                    b.HasKey("IDPublicacion", "IDUsuario");

                    b.HasIndex("IDUsuario");

                    b.ToTable("PublicacionesVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Property<int>("IDRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDRecompensa"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IDRecompensa");

                    b.ToTable("Recompensas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.Property<int>("IDRecompensaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDRecompensaUsuario"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaObtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IDRecompensa")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("IDRecompensaUsuario");

                    b.HasIndex("IDRecompensa");

                    b.HasIndex("UsersId");

                    b.ToTable("RecompensasUsuario", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDRespuesta"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IDPublicacion")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("RespuestaCorrecta")
                        .HasColumnType("boolean");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("IDRespuesta");

                    b.HasIndex("IDPublicacion");

                    b.HasIndex("UsersId");

                    b.ToTable("Respuestas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.Property<int>("IDRespuesta")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Positivo")
                        .HasColumnType("boolean");

                    b.HasKey("IDRespuesta", "IDUsuario");

                    b.HasIndex("IDUsuario");

                    b.ToTable("RespuestasVotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaEstadoModel", b =>
                {
                    b.Property<int>("IDEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEstado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDEstado");

                    b.HasIndex("Estado")
                        .IsUnique()
                        .HasDatabaseName("UQ_SesionAyudaEstado_Estado");

                    b.ToTable("SesionAyudaEstado", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaModel", b =>
                {
                    b.Property<Guid>("IDSesion")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("IDEstado")
                        .HasColumnType("integer");

                    b.Property<int>("IDReserva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDSesion");

                    b.HasIndex("IDEstado");

                    b.HasIndex("IDReserva")
                        .IsUnique()
                        .HasDatabaseName("IX_SesionAyuda_Reserva");

                    b.HasIndex("Dominio", "NombreSala")
                        .IsUnique()
                        .HasDatabaseName("UQ_SesionAyuda_Sala");

                    b.ToTable("SesionAyuda", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeLecturaModel", b =>
                {
                    b.Property<int>("IDMensaje")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("IDMensaje", "IDUsuario");

                    b.HasIndex("IDUsuario")
                        .HasDatabaseName("IX_SAChatMsgRead_User");

                    b.ToTable("SolicitudAyudaChatMensajeLectura", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.Property<int>("IDMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDMensaje"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IDChat")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("IDMensaje");

                    b.HasIndex("IDChat")
                        .HasDatabaseName("IX_SAChatMsg_Chat");

                    b.HasIndex("IDChat", "CreateDate")
                        .HasDatabaseName("IX_SAChatMsg_ChatDate");

                    b.ToTable("SolicitudAyudaChatMensaje", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.Property<int>("IDChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDChat"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuarioAyudante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("IDChat");

                    b.HasIndex("IDUsuarioAyudante")
                        .HasDatabaseName("IX_SAChat_Ayudante");

                    b.HasIndex("IDSolicitudAyuda", "IDUsuarioAyudante")
                        .IsUnique()
                        .HasDatabaseName("UQ_SAChat_SolicitudAyudante");

                    b.ToTable("SolicitudAyudaChat", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatParticipanteModel", b =>
                {
                    b.Property<int>("IDChat")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("Rol")
                        .HasColumnType("smallint");

                    b.HasKey("IDChat", "IDUsuario");

                    b.HasIndex("IDChat", "Rol")
                        .IsUnique()
                        .HasDatabaseName("UQ_SCP_ChatRol");

                    b.ToTable("SolicitudAyudaChatParticipante", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.Property<int>("IDDisponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDisponibilidad"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("Estado")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDDisponibilidad");

                    b.HasIndex("IDSolicitudAyuda")
                        .HasDatabaseName("IX_SAD_Solicitud");

                    b.HasIndex("Estado", "Inicio")
                        .HasDatabaseName("IX_SAD_EstadoTiempo");

                    b.ToTable("SolicitudAyudaDisponibilidad", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEstadoModel", b =>
                {
                    b.Property<int>("IDEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEstado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDEstado");

                    b.HasIndex("Estado")
                        .IsUnique()
                        .HasDatabaseName("UQ_SolicitudAyudaEstado_Estado");

                    b.ToTable("SolicitudAyudaEstado", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEtiquetasModel", b =>
                {
                    b.Property<int>("IDSolicitudAyudaEtiquetas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDSolicitudAyudaEtiquetas"));

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("integer");

                    b.Property<int>("IDEtiqueta")
                        .HasColumnType("integer");

                    b.HasKey("IDSolicitudAyudaEtiquetas", "IDSolicitudAyuda", "IDEtiqueta");

                    b.HasIndex("IDEtiqueta");

                    b.HasIndex("IDSolicitudAyuda", "IDEtiqueta")
                        .IsUnique()
                        .HasDatabaseName("UX_SolicitudAyudaEtiquetas");

                    b.ToTable("SolicitudAyudaEtiquetas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaHistorialModel", b =>
                {
                    b.Property<int>("IDHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDHistorial"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte?>("EstadoAnterior")
                        .HasColumnType("smallint");

                    b.Property<byte>("EstadoNuevo")
                        .HasColumnType("smallint");

                    b.Property<int>("IDSolicitudAyuda")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UserIdAccion")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("IDHistorial");

                    b.HasIndex("UserIdAccion");

                    b.HasIndex("IDSolicitudAyuda", "CreateDate")
                        .HasDatabaseName("IX_SAH_Solicitud");

                    b.ToTable("SolicitudAyudaHistorial", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.Property<int>("IDSolicitudAyuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDSolicitudAyuda"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("IDEstado")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuarioSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<decimal>("IncrementoPorHora")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("Lenguaje")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("RecompensaBase")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Urgencia")
                        .HasColumnType("smallint");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("IDSolicitudAyuda");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("IX_SA_Vencimiento");

                    b.HasIndex("IDEstado")
                        .HasDatabaseName("IX_SA_IDEstado");

                    b.HasIndex("IDUsuarioSolicitante")
                        .HasDatabaseName("IX_SA_Solicitante");

                    b.HasIndex("UsersId");

                    b.ToTable("SolicitudAyuda", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.Property<int>("IDReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDReserva"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("Estado")
                        .HasColumnType("smallint");

                    b.Property<int>("IDDisponibilidad")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuarioAyudante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IDReserva");

                    b.HasIndex("IDDisponibilidad")
                        .IsUnique()
                        .HasDatabaseName("UX_SolRes_Disponibilidad_Activa")
                        .HasFilter("(\"Estado\" IN (0,1,2))");

                    b.HasIndex("IDUsuarioAyudante", "Estado")
                        .HasDatabaseName("IX_SolRes_Ayudante");

                    b.ToTable("SolicitudAyudaReserva", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.TerminosCondicionesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TerminosCondiciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.TerminosCondicionesSesionAyudaModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("IdTyC")
                        .HasColumnType("integer");

                    b.Property<Guid>("IDSesion")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aceptado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAceptado")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "IdTyC", "IDSesion");

                    b.HasIndex("IDSesion");

                    b.HasIndex("IdTyC");

                    b.ToTable("TerminosCondicionesSesionAyuda", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.TextoPrediccionModel", b =>
                {
                    b.Property<int>("IDTextoPrediccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDTextoPrediccion"));

                    b.Property<string>("Etiquetas")
                        .HasColumnType("text");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.HasKey("IDTextoPrediccion");

                    b.ToTable("TextoPredicciones", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.UserFiltersModel", b =>
                {
                    b.Property<int>("IDFilter")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDFilter", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFilters", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.UsersForumModel", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("text");

                    b.Property<bool>("HasSeenIntroLabels")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeenIntroLiveHelp")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeenIntroPublications")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeenIntroUsers")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageForum")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastTimeConnectedForum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongDescriptionForum")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Onboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescriptionForum")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.ToTable("UsersForum", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.Property<int>("IDUsuarioMedalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuarioMedalla"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IDMedalla")
                        .HasColumnType("integer");

                    b.Property<string>("IDUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("IDUsuarioMedalla");

                    b.HasIndex("IDMedalla");

                    b.HasIndex("IDUsuario");

                    b.ToTable("UsuariosMedallas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.RefreshToken", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", "Users")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.RolesClaim", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Roles", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersClaims", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithMany("UsersClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersLogin", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithMany("UsersLogin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersRoles", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.UsersToken", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithMany("UsersTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Models.ArchivoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Archivos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("Archivos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.DenunciaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Denuncias")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("Denuncias")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Publicacion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaPublicacionModel", b =>
                {
                    b.HasOne("Core.Domain.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("EtiquetasPublicaciones")
                        .HasForeignKey("IDEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("EtiquetasPublicacion")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.FilterModel", b =>
                {
                    b.HasOne("Core.Domain.Models.FilterTypeModel", "FilterType")
                        .WithMany("Filters")
                        .HasForeignKey("IDFilterType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterType");
                });

            modelBuilder.Entity("Core.Domain.Models.GroupFiltersModel", b =>
                {
                    b.HasOne("Core.Domain.Models.FilterModel", "Filter")
                        .WithMany("GroupFilters")
                        .HasForeignKey("IDFilter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.GroupModel", "Group")
                        .WithMany("GroupFilters")
                        .HasForeignKey("IDGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionGuardadaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesGuardadas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "Usuario")
                        .WithMany("PublicacionesGuardadas")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", null)
                        .WithMany("Publicaciones")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("PublicacionesVotos")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "Usuario")
                        .WithMany("PublicacionesVotos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaUsuarioModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RecompensaModel", "Recompensa")
                        .WithMany("RecompensasUsuarios")
                        .HasForeignKey("IDRecompensa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", null)
                        .WithMany("RecompensasUsuarios")
                        .HasForeignKey("UsersId");

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.PublicacionModel", "Publicacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("IDPublicacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("UsersId");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaVotoModel", b =>
                {
                    b.HasOne("Core.Domain.Models.RespuestaModel", "Respuesta")
                        .WithMany("RespuestasVotos")
                        .HasForeignKey("IDRespuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "Usuario")
                        .WithMany("RespuestasVotos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respuesta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SesionAyudaEstadoModel", "SesionAyudaEstado")
                        .WithMany("Sesiones")
                        .HasForeignKey("IDEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.SolicitudAyudaReservaModel", "Reserva")
                        .WithOne("Sesion")
                        .HasForeignKey("Core.Domain.Models.SesionAyudaModel", "IDReserva")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("SesionAyudaEstado");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeLecturaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatMensajeModel", "Mensaje")
                        .WithMany("Lecturas")
                        .HasForeignKey("IDMensaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatModel", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("IDChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Chats")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatParticipanteModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaChatModel", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("IDChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEtiquetasModel", b =>
                {
                    b.HasOne("Core.Domain.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("SolicitudAyudaEtiquetas")
                        .HasForeignKey("IDEtiqueta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("SolicitudAyudaEtiquetas")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaHistorialModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaModel", "Solicitud")
                        .WithMany("Historial")
                        .HasForeignKey("IDSolicitudAyuda")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "UsuarioAccion")
                        .WithMany("SolicitudAyudaHistorial")
                        .HasForeignKey("UserIdAccion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioAccion");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaEstadoModel", "SolicitudAyudaEstado")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IDEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", null)
                        .WithMany("SolicitudesAyuda")
                        .HasForeignKey("UsersId");

                    b.Navigation("SolicitudAyudaEstado");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", "Disponibilidad")
                        .WithMany("Reservas")
                        .HasForeignKey("IDDisponibilidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "UsuarioAyudante")
                        .WithMany("SolicitudesAyudaReserva")
                        .HasForeignKey("IDUsuarioAyudante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Disponibilidad");

                    b.Navigation("UsuarioAyudante");
                });

            modelBuilder.Entity("Core.Domain.Models.TerminosCondicionesSesionAyudaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.SesionAyudaModel", "SesionAyuda")
                        .WithMany("TerminosCondiciones")
                        .HasForeignKey("IDSesion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Domain.Models.TerminosCondicionesModel", "TerminosCondiciones")
                        .WithMany("TerminosCondicionesSesionesAyuda")
                        .HasForeignKey("IdTyC")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SesionAyuda");

                    b.Navigation("TerminosCondiciones");
                });

            modelBuilder.Entity("Core.Domain.Models.UserFiltersModel", b =>
                {
                    b.HasOne("Core.Domain.Models.FilterModel", "Filter")
                        .WithMany("UserFilters")
                        .HasForeignKey("IDFilter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithMany("UserFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Models.UsersForumModel", b =>
                {
                    b.HasOne("Core.Domain.IdentityModels.Users", "User")
                        .WithOne("UsersForum")
                        .HasForeignKey("Core.Domain.Models.UsersForumModel", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Models.UsuarioMedallaModel", b =>
                {
                    b.HasOne("Core.Domain.Models.MedallaModel", "Medalla")
                        .WithMany("UsuariosMedallas")
                        .HasForeignKey("IDMedalla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.IdentityModels.Users", "Usuario")
                        .WithMany("UsuarioMedallas")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medalla");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.Roles", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Core.Domain.IdentityModels.Users", b =>
                {
                    b.Navigation("Publicaciones");

                    b.Navigation("PublicacionesGuardadas");

                    b.Navigation("PublicacionesVotos");

                    b.Navigation("RecompensasUsuarios");

                    b.Navigation("Respuestas");

                    b.Navigation("RespuestasVotos");

                    b.Navigation("SolicitudAyudaHistorial");

                    b.Navigation("SolicitudesAyuda");

                    b.Navigation("SolicitudesAyudaReserva");

                    b.Navigation("UserFilters");

                    b.Navigation("UserRefreshTokens");

                    b.Navigation("UsersClaims");

                    b.Navigation("UsersForum")
                        .IsRequired();

                    b.Navigation("UsersLogin");

                    b.Navigation("UsersTokens");

                    b.Navigation("UsuarioMedallas");
                });

            modelBuilder.Entity("Core.Domain.Models.EtiquetaModel", b =>
                {
                    b.Navigation("EtiquetasPublicaciones");

                    b.Navigation("SolicitudAyudaEtiquetas");
                });

            modelBuilder.Entity("Core.Domain.Models.FilterModel", b =>
                {
                    b.Navigation("GroupFilters");

                    b.Navigation("UserFilters");
                });

            modelBuilder.Entity("Core.Domain.Models.FilterTypeModel", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Core.Domain.Models.GroupModel", b =>
                {
                    b.Navigation("GroupFilters");
                });

            modelBuilder.Entity("Core.Domain.Models.MedallaModel", b =>
                {
                    b.Navigation("UsuariosMedallas");
                });

            modelBuilder.Entity("Core.Domain.Models.PublicacionModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Denuncias");

                    b.Navigation("EtiquetasPublicacion");

                    b.Navigation("PublicacionesGuardadas");

                    b.Navigation("PublicacionesVotos");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Core.Domain.Models.RecompensaModel", b =>
                {
                    b.Navigation("RecompensasUsuarios");
                });

            modelBuilder.Entity("Core.Domain.Models.RespuestaModel", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Denuncias");

                    b.Navigation("RespuestasVotos");
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaEstadoModel", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Core.Domain.Models.SesionAyudaModel", b =>
                {
                    b.Navigation("TerminosCondiciones");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatMensajeModel", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaChatModel", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaDisponibilidadModel", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaEstadoModel", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaModel", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Historial");

                    b.Navigation("SolicitudAyudaEtiquetas");
                });

            modelBuilder.Entity("Core.Domain.Models.SolicitudAyudaReservaModel", b =>
                {
                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("Core.Domain.Models.TerminosCondicionesModel", b =>
                {
                    b.Navigation("TerminosCondicionesSesionesAyuda");
                });
#pragma warning restore 612, 618
        }
    }
}
